### empty: error
POST http://localhost:8080/inference
#POST https://api.posthaste.pro/shipment/inference
Content-Type: multipart/form-data; boundary=boundary

### prompt
POST http://localhost:8080/inference
#POST https://api.posthaste.pro/shipment/inference
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="prompt"
Content-Type: text/plain

Please create a shipment from 1066HK Amsterdam, Heusdenstraat 12, Netherlands.
The recipient is Jane Smith and her address is 150-12 Parsons Bld, Jamaica, NY, 11432, US.
The shipment weight is 2.5 kg, and the dimensions are 30 cm x 20 cm x 10 cm.
The shipment contains one laptop and a charger with a value of $1000.
The recipient is Jane Smith his phone number is 6707028116. His email is test@posthaste.pro.
--boundary--

### PDF
POST http://localhost:8080/inference
#POST https://api.posthaste.pro/shipment/inference
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file.pdf"
Content-Type: application/pdf

< /Users/4135664/Documents/Commercial-Invoice-Regular.pdf
--boundary--

<> 2025-12-21T074134.200.json

### both prompt and PDF
POST http://localhost:8080/inference
#POST https://api.posthaste.pro/shipment/inference
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="prompt"
Content-Type: text/plain

Please create a shipment from 1066HK Amsterdam, Heusdenstraat 12, Netherlands.
The recipient is Jane Smith and her address is 150-12 Parsons Bld, Jamaica, NY, 11432, US.
The shipment weight is 2.5 kg, and the dimensions are 30 cm x 20 cm x 10 cm.
The shipment contains one laptop and a charger with a value of $1000.
The recipient is Jane Smith his phone number is 6707028116. His email is test@posthaste.pro.
--boundary
Content-Disposition: form-data; name="file"; filename="file.pdf"
Content-Type: application/pdf

< /Users/4135664/Documents/Commercial-Invoice-Regular.pdf
--boundary--
