POST http://localhost:8080/quotes
#POST https://api.posthaste.pro/shipment/quotes
Content-Type: application/json

{
  "shipper": {
    "name": "Mr. Smith",
    "postalCode": "11432",
    "city": "New York",
    "addressLine1": "50-32 154th Street",
    "stateProvince": "NY",
    "countryCode": "US",
    "phone": "111-222-4444",
    "email": ""
  },
  "recipient": {
    "name": "Csaba Kavai",
    "postalCode": "1101",
    "city": "Budapest",
    "addressLine1": "Lajos út 12/A 2/4",
    "stateProvince": "",
    "countryCode": "HU",
    "phone": "06707028116",
    "email": "test@posthaste.pro"
  },
  "packages": [
    {
      "weight": {
        "value": 2.5,
        "unit": "kg"
      },
      "dimensions": {
        "length": 11,
        "width": 8,
        "height": 15,
        "unit": "cm"
      }
    }
  ],
  "commodities": [
    {
      "description": "laptop and a charger",
      "quantity": 1,
      "harmonizedTariffCode": "999999",
      "countryOfOrigin": "US",
      "value": 1800,
      "valueCurrency": "EUR"
    }
  ]
}
